### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by KristjanESPERANTO** [pietervdvn/Mangrove-reviews-typescript#1]
I'm getting a 404 response. What I'm doing wrong?

My code:
```js
import { MangroveReviews } from "mangrove-reviews-typescript";

const subReviews = await MangroveReviews.getReviews({ sub: "geo:51.4954589,11.9659188", q: "verwöner", u: 30, issuers: true, maresi_subjects: true });

console.log(subReviews.reviews);
```

The the top of the error message:
```node
/###/node_modules/mangrove-reviews-typescript/node_modules/axios/dist/node/axios.cjs:1913
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 404
    at settle (/###/node_modules/mangrove-reviews-typescript/node_modules/axios/dist/node/axios.cjs:1913:12)
    at IncomingMessage.handleStreamEnd (/###/node_modules/mangrove-reviews-typescript/node_modules/axios/dist/node/axios.cjs:2995:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  ```

**Comment by KristjanESPERANTO** [comment]
@pietervdvn Did you noticed this issue?

**Comment by pietervdvn** [comment]
Talk about reviving old issues ;)

The mangrove documentation is horribly confusing. I've now added some code that automatically converts everything in the required format.

Use version 1.3.0 and your code above should work.
